### PR TITLE
Remove WET-BOEW files, Use CDTS. Update WET 4.0.29

### PR DESCRIPTION
**Pull request by smellems**
This removes all files from WET from this repo.  The files are called from the canada.ca cdts.

It make updates easier since you only have to change the version number in config.yml. I updated WET to 4.2.29 from 4.2.26.

I moved the `blog.css` file that was under the wet-boew folder to the css folder and renamed it to `blog2.css` since there was another file with the same name.

### CODE REVIEW

**Comment by smellems** [comment]
Closes #36

**Comment by jmealing** [comment]
Thanks for pointing out a better way - we're actually converting this space into redirects and are moving to:

https://github.com/canada-ca/blog-dto (EN)
https://github.com/canada-ca/blogue-btn (FR)

The new space will be live once the design refresh launches. This would work also well in new space once the CDTS is updated with the design refresh.

**Comment by smellems** [comment]
Ok, I like how your linking strait to Github for the latest WET version!

Is the restructuring only to split French and English?

You might to merge this anyway since it does'nt change anything and removes alot of files from this repo.

**Comment by jmealing** [comment]
The reason for the restructuring is so we can use custom domain names - blog.canada.ca and blogue.canada.ca. We needed the two repos to reference the two domains.

**Pull request merged**
